// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("e0160fb3-4ed7-4055-bab9-e16294d8c19e"),
	startsWith("a73b2537-013b-467f-9aa1-b1c5de33708f"),
	endsWith("58a1427f-26e7-4255-861b-1e764c383c37"),
	between("37a857e0-6885-4f4c-94b0-7bb70d662a70"),
	greater("e6326dad-d5bd-4ce3-a856-3fb86bb08784"),
	greaterEqual("7bf31996-ebbb-4583-9fb7-69d5ff338694"),
	equal("6ed93085-7dcd-4709-94a6-c941591807b9"),
	notEqual("a055ba6e-e6ab-4a46-aa20-bcc00382ea89"),
	smaller("dd1813c5-cb37-4e10-94a2-49ba189ff7da"),
	smallerEqual("a123c054-d83f-4062-b60c-e5b474bbd641"),
	empty("30cad405-755a-4969-8968-13faa19c6781"),
	notEmpty("cafaac45-3e4f-43ec-9be9-e80584180d03");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
