// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("55735195-037e-4bc0-a412-6f1ff27e905d"),
	English("43097eb4-4959-4f9d-a513-f75dd164725e"),
	French("f1d38e17-94f6-431b-95db-76982e87f731"),
	German("fc03bd1a-766b-4201-b13d-ee46ab27947f"),
	Hindi("b36bd904-862a-46b1-8584-f211b5a67ea5"),
	Portuguese("eb60b4b3-afd7-42db-991b-59f5c9b05c13"),
	Spanish("9774ed0b-2773-4350-acdd-881b8410276d"),
	Turkish("f165be91-73dd-4374-8705-a460a06d43b9");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
