// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("cf0834a3-063b-4626-8201-61eca9ce36b5"),
	Geocodio("f3db986f-cfa4-4a0c-8de8-23f786bfb21a"),
	LocationIQ("a489463f-f211-47ad-ba11-3fed6fe5260f"),
	MapQuest("5af84868-f40e-4c53-9fc7-b00c8f1195dc");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
