// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Course_ScheduleTrainingEventBuilder(
		myfirstmodule.proxies.Course _course
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Course_ScheduleTrainingEvent");
		builder = builder.withParam("Course", _course);
		return builder;
	}

	public static void aCT_Course_ScheduleTrainingEvent(
		IContext context,
		myfirstmodule.proxies.Course _course
	)
	{
		aCT_Course_ScheduleTrainingEventBuilder(
				_course
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Registration_SaveBuilder(
		myfirstmodule.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Registration_Save");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static void aCT_Registration_Save(
		IContext context,
		myfirstmodule.proxies.Registration _registration
	)
	{
		aCT_Registration_SaveBuilder(
				_registration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TrainingEvent_SaveValidateBuilder(
		myfirstmodule.proxies.TrainingEvent _trainingEvent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_TrainingEvent_SaveValidate");
		builder = builder.withParam("TrainingEvent", _trainingEvent);
		return builder;
	}

	public static void aCT_TrainingEvent_SaveValidate(
		IContext context,
		myfirstmodule.proxies.TrainingEvent _trainingEvent
	)
	{
		aCT_TrainingEvent_SaveValidateBuilder(
				_trainingEvent
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aDE_Registration_CalculateTotalNumberOfRegistrationsBuilder(
		myfirstmodule.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ADE_Registration_CalculateTotalNumberOfRegistrations");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static void aDE_Registration_CalculateTotalNumberOfRegistrations(
		IContext context,
		myfirstmodule.proxies.Registration _registration
	)
	{
		aDE_Registration_CalculateTotalNumberOfRegistrationsBuilder(
				_registration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder myFirstLogicBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.MyFirstLogic");
		return builder;
	}

	public static void myFirstLogic(IContext context)
	{
		myFirstLogicBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCH_TrainingEvent_CalculateEndDateBuilder(
		myfirstmodule.proxies.TrainingEvent _trainingEvent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.OCH_TrainingEvent_CalculateEndDate");
		builder = builder.withParam("TrainingEvent", _trainingEvent);
		return builder;
	}

	public static void oCH_TrainingEvent_CalculateEndDate(
		IContext context,
		myfirstmodule.proxies.TrainingEvent _trainingEvent
	)
	{
		oCH_TrainingEvent_CalculateEndDateBuilder(
				_trainingEvent
			)
			.execute(context);
	}
}
