// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("ffce17bc-7fd9-4f96-bed5-70b2c955c320"),
	low("531ae6af-148f-4967-ad9f-41c9aea642a6"),
	medium("34b64dfd-9c27-43bb-bb09-66ab7917ebe2"),
	high("fd710c91-595e-4499-b963-05aa839d04d8"),
	custom("cc97879d-1d07-446a-af56-bb4303e7a5cc");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
