// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("88a4b732-0fdd-498a-8dfb-195e6dcc30d2"),
	low("0a702299-8af3-4e3e-a279-a821ca999e61"),
	medium("b1069d6c-e577-4f9c-8de9-1c7345ff78ad"),
	high("813db547-e596-4e27-9a1c-bbb5f62abba5"),
	custom("647ead4b-b44f-470f-b19b-62bea9e89d24");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
