// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("484beaf2-6294-43ac-9397-c392ea53dd6a"),
	startsWith("c471a47a-bc60-4e05-98ac-c94cea76e214"),
	endsWith("47706859-b16d-4ece-bf69-208b33304541"),
	between("53d519d1-1dcf-44d6-a5e6-f668a0b199de"),
	greater("6785ef80-d26a-480f-983e-0bd59213798a"),
	greaterEqual("7b03d7db-a854-4cdd-b616-4828ba8f63ab"),
	equal("740996b4-7ee1-4791-9857-7e7172e78966"),
	notEqual("3e8d32cf-ceb2-49dc-8d22-efa75f1cf032"),
	smaller("2808f39d-e0fc-4346-9965-2ac7cbea9b93"),
	smallerEqual("bf218a99-5f61-4243-83ba-327882f915c2"),
	empty("f6952025-1f1e-4a47-8bdc-54f2e4789524"),
	notEmpty("d83d9952-377a-4f80-9197-54a4155a61a0");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
