// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("f8bc814f-8f3d-4d9a-9153-49d43f375bcc"),
	English("10c78ccf-515f-401c-88ec-8f50e96c7f62"),
	French("e1966035-e529-4620-b707-0fcd0cfddf12"),
	German("18ab8e9e-6b3e-4407-9847-c49154dfe045"),
	Hindi("196beab0-edac-487e-a435-cfb6ec69b36e"),
	Portuguese("2320652f-f8e2-46e4-8228-366c1b32c970"),
	Spanish("86390f19-3167-48d0-bd41-fb10d9d94a50"),
	Turkish("e546cf68-8172-4d4a-a30b-2921035be016");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
